<!DOCTYPE html><html lang="es" >

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  
  
  
    <meta name="generator" content="Wowchemy 5.3.0 for Hugo" />
  

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Alexis Sáez" />

  
  
  
    
  
  <meta name="description" content="Introducción al estudio de excepciones en Python." />

  
  <link rel="alternate" hreflang="es" href="https://imalexissaez.github.io/python-basic/excepciones/" />

  









  




  
  

  
  
  
    <meta name="theme-color" content="#1565c0" />
  

  
  

  
  
  
  
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha256-FMvZuGapsJLjouA6k7Eo2lusoAX9i0ShlWFG6qt7SLc=" crossorigin="anonymous" media="print" onload="this.media='all'">

    
    
    
    
      
      
    
    
    

    
    
    
    

    
    
    

    

    
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      
        
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
  

  
  
  

  
  
  
  
  
  <link rel="stylesheet" href="/css/wowchemy.04560f2d852a4f507fd3445a9ee3c72d.css" />

  



  

  

  




  
  
  

  
    <link rel="alternate" href="/python-basic/excepciones/index.xml" type="application/rss+xml" title="Infinitos Contrastes" />
  

  
    <link rel="manifest" href="/manifest.webmanifest" />
  

  <link rel="icon" type="image/png" href="/media/icon_hubd324007acfbf71c468514de6d8e3809_36197_32x32_fill_lanczos_center_3.png" />
  <link rel="apple-touch-icon" type="image/png" href="/media/icon_hubd324007acfbf71c468514de6d8e3809_36197_180x180_fill_lanczos_center_3.png" />

  <link rel="canonical" href="https://imalexissaez.github.io/python-basic/excepciones/" />

  
  
  
  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary" />
  
  <meta property="og:site_name" content="Infinitos Contrastes" />
  <meta property="og:url" content="https://imalexissaez.github.io/python-basic/excepciones/" />
  <meta property="og:title" content="Excepciones | Infinitos Contrastes" />
  <meta property="og:description" content="Introducción al estudio de excepciones en Python." /><meta property="og:image" content="https://imalexissaez.github.io/media/icon_hubd324007acfbf71c468514de6d8e3809_36197_512x512_fill_lanczos_center_3.png" />
    <meta property="twitter:image" content="https://imalexissaez.github.io/media/icon_hubd324007acfbf71c468514de6d8e3809_36197_512x512_fill_lanczos_center_3.png" /><meta property="og:locale" content="es" />
  
    
      <meta property="og:updated_time" content="2019-05-06T00:01:01&#43;01:00" />
    
  

  



  

  





  <title>Excepciones | Infinitos Contrastes</title>
</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class="page-wrapper   " data-wc-page-id="051a7f566c80af1c8435df8880f8206c" >

  
  
  
  
  
  
  
  
  
  <script src="/js/wowchemy-init.min.fccf491147236875a545acccaebaf369.js"></script>

  




  <div class="page-header">
    












<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container-xl">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Infinitos Contrastes</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Barra de navegación">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Infinitos Contrastes</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#projects"><span>Proyectos</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Blog</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about"><span>Acerca de</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">

      
      
        
      

      
      

      
      

      
      

    </ul>

  </div>
</nav>


  </div>

  <div class="page-body">
    





<div class="container-fluid docs">
  <div class="row flex-xl-nowrap">
    <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
      <form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-md-3 w-100" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <div class="d-flex">
      <span class="d-md-none pl-1 flex-grow-1 text-left overflow-hidden">
        
          Presentación del proyecto
        
      </span>
      <span><i class="fas fa-chevron-down"></i></span>
    </div>
  </button>

  
</form>

<nav class="collapse docs-links" id="docs-nav">
  
  
  
  
  
  

  
  
    

    
      

      


  
    
    
    
    
      
    
    

    
      <ul class="nav docs-sidenav">
        <li class=""><a href="/python-basic/">Presentación del proyecto</a></li>
    
      


  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/introduccion/">Introducción</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/tipos-y-variables/">Tipos y variables</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/condicionales/">Condicionales</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/bucles/">Bucles</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/generadores/">Generadores</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link  active" href="/python-basic/excepciones/">Excepciones</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/poo/">Programación OO</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/modulos-y-archivos/">Métodos y archivos</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/interfaces/">Interfaces</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/bases-de-datos/">Bases de datos</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/practica/">Práctica guiada</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/python-basic/temas-avanzados/">Temas avanzados</a>
    

    
      </div>
    

      
    

    
      </ul>
    

  
</nav>

    </div>

    
    
    <div class="d-none d-xl-block col-xl-2 docs-toc">
      

      <ul class="nav toc-top">
        <li><a href="#" id="back_to_top" class="docs-toc-title">En esta página</a></li>
      </ul>

      <nav id="TableOfContents">
  <ul>
    <li><a href="#excepciones-i">Excepciones I</a>
      <ul>
        <li><a href="#vídeo">Vídeo</a></li>
        <li><a href="#notas-personales">Notas personales</a></li>
        <li><a href="#código-fuente">Código fuente</a></li>
      </ul>
    </li>
    <li><a href="#excepciones-ii">Excepciones II</a>
      <ul>
        <li><a href="#vídeo-1">Vídeo</a></li>
        <li><a href="#notas-personales-1">Notas personales</a></li>
        <li><a href="#código-fuente-1">Código fuente</a></li>
      </ul>
    </li>
    <li><a href="#excepciones-iii">Excepciones III</a>
      <ul>
        <li><a href="#vídeo-2">Vídeo</a></li>
        <li><a href="#notas-personales-2">Notas personales</a></li>
        <li><a href="#código-fuente-2">Código fuente</a></li>
      </ul>
    </li>
  </ul>
</nav>

      
    </div>
    

    <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

      <article class="article">

        <div class="docs-article-container">
          

          <h1>Excepciones</h1>

          <div class="article-style">
            <h2 id="excepciones-i">Excepciones I</h2>
<h3 id="vídeo">Vídeo</h3>

<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;">
  <iframe src="https://www.youtube.com/embed/2MaAs7XU2T0" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen title="YouTube Video"></iframe>
</div>

<h3 id="notas-personales">Notas personales</h3>
<p>Una <strong>excepción</strong> es un error que acontece durante la ejecución de un programa. La sintaxis del código es correcta, pero, en el momento de ejecutarse el algoritmo, sucede &lsquo;&lsquo;algo inesperado&rsquo;&rsquo;.</p>
<p>Para ilustrar la aparición de excepciones, trabajemos con el siguiente código:</p>
<pre><code class="language-python">def suma(num1, num2):
    return num1 + num2


def resta(num1, num2):
    return num1 - num2


def multiplica(num1, num2):
    return num1 * num2


def divide(num1, num2):
    return num1 / num2


op1 = (int(input(&quot;Introduce el primer número: &quot;)))
op2 = (int(input(&quot;Introduce el segundo número: &quot;)))

print(&quot;Operaciones disponibles: &quot;)
print(&quot;- Suma&quot;)
print(&quot;- Resta&quot;)
print(&quot;- Multiplica&quot;)
print(&quot;- Divide&quot;)

operacion = input(&quot;Introduce la operación a realizar: &quot;)

if operacion == &quot;Suma&quot;:
    print(suma(op1, op2))
elif operacion == &quot;Resta&quot;:
    print(resta(op1, op2))
elif operacion == &quot;Multiplica&quot;:
    print(multiplica(op1, op2))
elif operacion == &quot;Divide&quot;:
    print(divide(op1, op2))
else:
    print(&quot;Operación no contemplada.&quot;)

print(&quot;Operación ejecutada. Continuación de ejecución del programa &quot;)
</code></pre>
<p>Un posible ejemplo de ejecución sería:</p>
<pre><code class="language-bash">Introduce el primer número: 16
Introduce el segundo número: 4
Operaciones disponibles: 
- Suma
- Resta
- Multiplica
- Divide
Introduce la operación a realizar: Multiplica
64
Operación ejecutada. Continuación de ejecución del programa
</code></pre>
<p>Sin embargo, si por accidente intentamos realizar una división entre 0:</p>
<pre><code class="language-bash">Introduce el primer número: 2
Introduce el segundo número: 0
Operaciones disponibles: 
- Suma
- Resta
- Multiplica
- Divide
Introduce la operación a realizar: Divide
Traceback (most recent call last):
  File &quot;prac21_excepciones1_1.py&quot;, line 35, in &lt;module&gt;
    print(divide(op1, op2))
  File &quot;prac21_excepciones1_1.py&quot;, line 14, in divide
    return num1 / num2
ZeroDivisionError: division by zero
</code></pre>
<p>De forma que el código se detiene en el preciso instante de la llamada a la función <code>divide()</code> y deja de ejecutar las restantes líneas (la instrucción <code>print()</code> final en esta ocasión), cuya importancia puede ser vital para nosotros.</p>
<p>Este tipo de situaciones se aborda mediante una <strong>captura</strong> o <strong>control de excepción</strong>. La idea es intentar realizar un bloque de código y, en el caso de no poderse llevar a cabo dicha acción, que al menos el resto de programa siga adelante.</p>
<p>Si nos fijamos en la <strong>pila de llamadas</strong> que nos muestran antes de arrojar el error:</p>
<pre><code class="language-bash">Traceback (most recent call last):
  File &quot;prac21_excepciones1_1.py&quot;, line 35, in &lt;module&gt;
    print(divide(op1, op2))
  File &quot;prac21_excepciones1_1.py&quot;, line 14, in divide
    return num1 / num2
ZeroDivisionError: division by zero
</code></pre>
<p>Leyendo de abajo hacia arriba, la instrucción <code>return num1 / num2</code>, ubicada en la línea 14 del código, arroja un error de división por cero (<code>ZeroDivisionError</code>). Para controlar esta circunstancia, usaremos un bloque de tipo:</p>
<pre><code class="language-python">try:
    instrucciones
except error:
    instrucciones
</code></pre>
<p>Así, nuestra función <code>divide()</code> la podríamos reescribir como sigue:</p>
<pre><code class="language-python">def divide(num1, num2):
    try:
        return num1 / num2
    except ZeroDivisionError:
        print(&quot;No se puede dividir entre 0.&quot;)
        return &quot;Operación errónea.&quot;
</code></pre>
<p>De manera que, replicando el anterior conflictivo ejemplo:</p>
<pre><code class="language-bash">Introduce el primer número: 2
Introduce el segundo número: 0
Operaciones disponibles: 
- Suma
- Resta
- Multiplica
- Divide
Introduce la operación a realizar: Divide
No se puede dividir entre 0.
Operación errónea.
Operación ejecutada. Continuación de ejecución del programa 
</code></pre>
<p>Apreciamos que la última línea de código, aquel <code>print()</code> final, ahora efectivamente sí llega a ejecutarse.</p>
<p>Por desgracia, no es el único punto conflictivo que presenta el código mostrado. Por ejemplo, ¿qué sucede si introducimos una cadena de texto en lugar de un número?</p>
<pre><code class="language-bash">Introduce el primer número: 3
Introduce el segundo número: a
Traceback (most recent call last):
  File &quot;prac21_excepciones1_1.py&quot;, line 22, in &lt;module&gt;
    op2 = (int(input(&quot;Introduce el segundo número: &quot;)))
ValueError: invalid literal for int() with base 10: 'a'
</code></pre>
<p><em>Python</em> arroja un error de tipo <code>ValueError</code> que también habríamos de controlar a través de un bloque <code>try</code> - <code>except</code>.</p>
<h3 id="código-fuente">Código fuente</h3>
<p>El código fuente y los posibles ficheros externos generados correspondientes a esta lección se encuentran disponibles para su consulta en la carpeta <code>/lecciones/21/</code> del <a href="https://github.com/ImAlexisSaez/curso-python-desde-0" target="_blank" rel="noopener">repositorio</a>.</p>
<h2 id="excepciones-ii">Excepciones II</h2>
<h3 id="vídeo-1">Vídeo</h3>

<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;">
  <iframe src="https://www.youtube.com/embed/HH3c6ZBvSx8" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen title="YouTube Video"></iframe>
</div>

<h3 id="notas-personales-1">Notas personales</h3>
<p>Recordemos el código final de la lección anterior:</p>
<pre><code class="language-python">def suma(num1, num2):
    return num1 + num2


def resta(num1, num2):
    return num1 - num2


def multiplica(num1, num2):
    return num1 * num2


def divide(num1, num2):
    try:
        return num1 / num2
    except ZeroDivisionError:
        print(&quot;No se puede dividir entre 0.&quot;)
        return &quot;Operación errónea.&quot;


op1 = (int(input(&quot;Introduce el primer número: &quot;)))
op2 = (int(input(&quot;Introduce el segundo número: &quot;)))

print(&quot;Operaciones disponibles: &quot;)
print(&quot;- Suma&quot;)
print(&quot;- Resta&quot;)
print(&quot;- Multiplica&quot;)
print(&quot;- Divide&quot;)

operacion = input(&quot;Introduce la operación a realizar: &quot;)

if operacion == &quot;Suma&quot;:
    print(suma(op1, op2))
elif operacion == &quot;Resta&quot;:
    print(resta(op1, op2))
elif operacion == &quot;Multiplica&quot;:
    print(multiplica(op1, op2))
elif operacion == &quot;Divide&quot;:
    print(divide(op1, op2))
else:
    print(&quot;Operación no contemplada.&quot;)

print(&quot;Operación ejecutada. Continuación de ejecución del programa.&quot;)
</code></pre>
<p>No obstante, este código es susceptible de presentar más errores. Por ejemplo, introduciendo una cadena de texto en lugar de un número cuando nos solicitan los datos.</p>
<p>Para solucionar ese detalle, podemos reescribir el correspondiente bloque de código como sigue:</p>
<pre><code class="language-python">try:
    op1 = (int(input(&quot;Introduce el primer número: &quot;)))
    op2 = (int(input(&quot;Introduce el segundo número: &quot;)))
except ValueError:
    print(&quot;Los valores introducidos no son correctos.&quot;)
</code></pre>
<p>El programa así modificado, presenta errores de lógica ahora, ya que si introducimos una cadena de texto como dato, <em>Python</em> no arroja error, pero continua la ejecución del programa y al intentar llevar a cabo cualquier operación de las disponibles, lanza un error de tipo <code>NameError</code>:</p>
<pre><code class="language-bash">Introduce el primer número: 5
Introduce el segundo número: a
Los valores introducidos no son correctos.
Operaciones disponibles: 
- Suma
- Resta
- Multiplica
- Divide
Introduce la operación a realizar: Suma
Traceback (most recent call last):
  File &quot;prac22_excepciones2_1.py&quot;, line 36, in &lt;module&gt;
    print(suma(op1, op2))
NameError: name 'op2' is not defined
</code></pre>
<p>Una manera de abordar esta problemática es mediante un bucle infinito de tipo <code>while</code>, forzando que el usuario introduzca valores admisibles para continuar la ejecución del programa:</p>
<pre><code class="language-python">while True:
    try:
        op1 = (int(input(&quot;Introduce el primer número: &quot;)))
        op2 = (int(input(&quot;Introduce el segundo número: &quot;)))
        break
    except ValueError:
        print(&quot;Los valores introducidos no son correctos. Inténtalo de nuevo.&quot;)
</code></pre>
<p>Siendo una posible ejecución del programa la que se muestra acto seguido:</p>
<pre><code class="language-bash">Introduce el primer número: 5
Introduce el segundo número: a
Los valores introducidos no son correctos. Inténtalo de nuevo.
Introduce el primer número: ag
Los valores introducidos no son correctos. Inténtalo de nuevo.
Introduce el primer número: 5
Introduce el segundo número: 0
Operaciones disponibles: 
- Suma
- Resta
- Multiplica
- Divide
Introduce la operación a realizar: Suma
5
Operación ejecutada. Continuación de ejecución del programa.
</code></pre>
<p>Elaboremos ahora una función <code>divide()</code> diferente a la vista en el ejemplo anterior:</p>
<pre><code class="language-python">def divide():
    op1 = (float(input(&quot;Dividendo: &quot;)))
    op2 = (float(input(&quot;Divisor: &quot;)))
    print(&quot;La división resulta: &quot; + str(op1 / op2))
    print(&quot;Cálculo finalizado.&quot;)


divide()
</code></pre>
<p>Como antes, el programa arroja excepciones si intentamos dividir por cero o introducimos cadenas de texto como datos. Capturémoslas de manera consecutiva:</p>
<pre><code class="language-python">def divide():
    try:
        op1 = (float(input(&quot;Dividendo: &quot;)))
        op2 = (float(input(&quot;Divisor: &quot;)))
        print(&quot;La división resulta: &quot; + str(op1 / op2))
    except ValueError:
        print(&quot;El valor introducido es erróneo.&quot;)
    except ZeroDivisionError:
        print(&quot;No se puede dividir entre cero.&quot;)
    print(&quot;Cálculo finalizado.&quot;)


divide()
</code></pre>
<p>Existe una alternativa genérica, aunque poco recomendable, que consiste en teclear <code>except:</code> sin más e imprimir un mensaje neutro de error. Captura una excepción de forma general, pero no informa sobre lo acontencido.</p>
<p>Por otro lado, cuando queremos que un código se ejecute siempre, existe la posibilidad de ubicarlo en el interior de una claúsula <code>finally</code>:</p>
<pre><code class="language-python">def divide():
    try:
        op1 = (float(input(&quot;Dividendo: &quot;)))
        op2 = (float(input(&quot;Divisor: &quot;)))
        print(&quot;La división resulta: &quot; + str(op1 / op2))
    except ValueError:
        print(&quot;El valor introducido es erróneo.&quot;)
    except ZeroDivisionError:
        print(&quot;No se puede dividir entre cero.&quot;)
    finally:
        print(&quot;Cálculo finalizado.&quot;)


divide()
</code></pre>
<p>Además, es posible también programar utilizando la combinación <code>try</code> - <code>finally</code>:</p>
<pre><code class="language-python">def divide():
    try:
        op1 = (float(input(&quot;Dividendo: &quot;)))
        op2 = (float(input(&quot;Divisor: &quot;)))
        print(&quot;La división resulta: &quot; + str(op1 / op2))
    finally:
        print(&quot;Cálculo finalizado.&quot;)


divide()
</code></pre>
<p>Veamos algunas posibles ejecuciones de este último bloque de código:</p>
<pre><code class="language-bash">Dividendo: 4
Divisor: 2
La división resulta: 2.0
Cálculo finalizado.
</code></pre>
<pre><code class="language-bash">Dividendo: aaa
Cálculo finalizado.
Traceback (most recent call last):
  File &quot;prac22_excepciones2_3.py&quot;, line 10, in &lt;module&gt;
    divide()
  File &quot;prac22_excepciones2_3.py&quot;, line 3, in divide
    op1 = (float(input(&quot;Dividendo: &quot;)))
ValueError: could not convert string to float: 'aaa'
</code></pre>
<pre><code class="language-bash">Dividendo: 5
Divisor: 0
Cálculo finalizado.
Traceback (most recent call last):
  File &quot;prac22_excepciones2_3.py&quot;, line 10, in &lt;module&gt;
    divide()
  File &quot;prac22_excepciones2_3.py&quot;, line 5, in divide
    print(&quot;La división resulta: &quot; + str(op1 / op2))
ZeroDivisionError: float division by zero
</code></pre>
<p>La cadena de texto <code>&quot;Cálculo finalizado&quot;</code> se muestra por pantalla, independientemente de la presencia o no de excepciones durante la ejecución del algoritmo.</p>
<p><em>Nota técnica</em>: toda instrucción <code>try</code> ha de estar acompañada bien de su correspondiente <code>except</code>, bien de <code>finally</code>, bien de ambas; pero no puede aparecer en solitario.</p>
<h3 id="código-fuente-1">Código fuente</h3>
<p>El código fuente y los posibles ficheros externos generados correspondientes a esta lección se encuentran disponibles para su consulta en la carpeta <code>/lecciones/22/</code> del <a href="https://github.com/ImAlexisSaez/curso-python-desde-0" target="_blank" rel="noopener">repositorio</a>.</p>
<h2 id="excepciones-iii">Excepciones III</h2>
<h3 id="vídeo-2">Vídeo</h3>

<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;">
  <iframe src="https://www.youtube.com/embed/dLH-oay4Bts" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen title="YouTube Video"></iframe>
</div>

<h3 id="notas-personales-2">Notas personales</h3>
<p>Estudiemos cómo lanzar excepciones, de forma intencionada, a través de la instrucción <code>raise</code>. Veremos su utilidad cuando trabajemos, más adelante, con clases.</p>
<p>Generemos un sencillo programa cuyo objetivo sea evaluar nuestra edad:</p>
<pre><code class="language-python">def evalua_edad(edad):
    if edad &lt; 20:
        return &quot;Eres muy joven.&quot;
    elif edad &lt; 40:
        return &quot;Eres joven.&quot;
    elif edad &lt; 65:
        return &quot;Eres maduro.&quot;
    elif edad &lt; 100:
        return &quot;Cuídate.&quot;


print(evalua_edad(18))  # Eres muy joven.
print(evalua_edad(70))  # Cuídate.
</code></pre>
<p>Sin embargo, la función así definida presenta este curioso comportamiento:</p>
<pre><code class="language-python">print(evalua_edad(-15))  # Eres muy joven.
</code></pre>
<p>Evidentemente, podemos arreglar esta situación mediante estructuras condicionales, pero veremos a continuación cómo emplear la instrucción <code>raise</code> para abordar el presente caso.</p>
<pre><code class="language-python">def evalua_edad(edad):
    if edad &lt; 0:
        raise TypeError(&quot;No se permiten edades negativas.&quot;)
    if edad &lt; 20:
        return &quot;Eres muy joven.&quot;
    elif edad &lt; 40:
        return &quot;Eres joven.&quot;
    elif edad &lt; 65:
        return &quot;Eres maduro.&quot;
    elif edad &lt; 100:
        return &quot;Cuídate.&quot;


print(evalua_edad(18))
print(evalua_edad(70))
print(evalua_edad(-15))
</code></pre>
<p>Al ejecutar el anterior programa, obtenemos:</p>
<pre><code class="language-bash">Eres muy joven.
Cuídate.
Traceback (most recent call last):
  File &quot;prac23_excepciones3_2.py&quot;, line 16, in &lt;module&gt;
    print(evalua_edad(-15))
  File &quot;prac23_excepciones3_2.py&quot;, line 3, in evalua_edad
    raise TypeError(&quot;No se permiten edades negativas.&quot;)
TypeError: No se permiten edades negativas.
</code></pre>
<p><em>Nota</em>: hemos de usar alguno de los tipos de error disponibles en <em>Python</em>, no pdemos cualquier cadena de texto sin más ahí. No obstante, dicho esto, cuando generemos clases podremos elaborar también errores personalizados.</p>
<p>Pasemos a programar un algoritmo que calcule la raíz cuadrada de un número mayor o igual que cero:</p>
<pre><code class="language-python">import math


def calcula_raiz(num):
    if num &lt; 0:
        raise ValueError(&quot;El número no puede ser negativo.&quot;)
    else:
        return math.sqrt(num)


op = (int(input(&quot;Introduce un número mayor o igual que cero: &quot;)))

print(calcula_raiz(op))

print(&quot;Programa terminado.&quot;)
</code></pre>
<p>Controlemos la excepción que aparece si introducimos un número negativo:</p>
<pre><code class="language-python">import math


def calcula_raiz(num):
    if num &lt; 0:
        raise ValueError(&quot;El número no puede ser negativo.&quot;)
    else:
        return math.sqrt(num)


op = (int(input(&quot;Introduce un número mayor o igual que cero: &quot;)))

try:
    print(calcula_raiz(op))
except ValueError as ErrorDeNumeroNegativo:
    print(ErrorDeNumeroNegativo)

print(&quot;Programa terminado.&quot;)
</code></pre>
<p>Un par de ejecuciones del anterior programa, por ejemplo, podrían ser:</p>
<pre><code class="language-bash">Introduce un número mayor o igual que cero: 144
12.0
Programa terminado.
</code></pre>
<pre><code class="language-bash">Introduce un número mayor o igual que cero: -144
El número no puede ser negativo.
Programa terminado.
</code></pre>
<h3 id="código-fuente-2">Código fuente</h3>
<p>El código fuente y los posibles ficheros externos generados correspondientes a esta lección se encuentran disponibles para su consulta en la carpeta <code>/lecciones/23/</code> del <a href="https://github.com/ImAlexisSaez/curso-python-desde-0" target="_blank" rel="noopener">repositorio</a>.</p>

          </div>

          



          
          
          <div class="article-widget">
            
<div class="post-nav">
  
  
</div>

          </div>
          
        </div>

        <div class="body-footer">
          <p>Última actualización el May 6, 2019</p>

          



          




          


        </div>

      </article>

      <footer class="site-footer">

  



  

  

  

  
  






  <p class="powered-by">
    
    
    
      
      
      
      
      
      
      Published with <a href="https://wowchemy.com/?utm_campaign=poweredby" target="_blank" rel="noopener">Wowchemy</a> — the free, <a href="https://github.com/wowchemy/wowchemy-hugo-modules" target="_blank" rel="noopener">open source</a> website builder that empowers creators.
    
  </p>
</footer>


    </main>
  </div>
</div>

  </div>

  <div class="page-footer">
    
    
  </div>

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Citar</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copiar
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Descargar
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/instant.page/5.1.0/instantpage.min.js" integrity="sha512-1+qUtKoh9XZW7j+6LhRMAyOrgSQKenQ4mluTR+cvxXjP1Z54RxZuzstR/H9kgPXQsVB8IW7DMDFUJpzLjvhGSQ==" crossorigin="anonymous"></script>

      
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      

      
      

      

      

    

    
    
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.2.2/anchor.min.js" integrity="sha512-I7w3ZdSFzw5j3jU3ZkNikBNeIrl3i+hEuEdwNmqUJvwNcaBUNcijnP2gd9DtGlgVYDplfjGoD8vTNsID+lCjqg==" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    
    
    

    
    

    
    
    
    

    
    <script src="/js/bootstrap.bundle.min.6aed84840afc03ab4d5750157f69c120.js"></script>

    
    

    
    
    
    
    
    
    
    
    
    <script src="/es/js/wowchemy.min.21586ccbb6e799494c5db261641a6c60.js"></script>

    






</body>
</html>
